import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <div className="text-red-900">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>main</div>
            <footer className="border-t-2 border-indigo-600">footer</footer>
        </div>
    );
}
